package com.example.moviementor.adapters;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.example.moviementor.R;
import com.example.moviementor.models.TrendingMovieViewModel;

import java.util.List;

public class TrendingMoviesAdapter extends RecyclerView.Adapter<TrendingMoviesAdapter.ViewHolder> {
    private final List<TrendingMovieViewModel> trendingMoviesList;

    public TrendingMoviesAdapter(final @NonNull List<TrendingMovieViewModel> trendingMoviesList) {
        this.trendingMoviesList = trendingMoviesList;
    }

    @Override
    public ViewHolder onCreateViewHolder(final @NonNull ViewGroup parent, final int viewType) {
        final LayoutInflater inflater = LayoutInflater.from(parent.getContext());

        // Inflate custom layout for singular trending movie
        final View trendingMovieItemView = inflater.inflate(R.layout.trending_movie_item, parent, false);

        // Return new view holder for inflated movie item
        return new ViewHolder(trendingMovieItemView);
    }

    @Override
    public void onBindViewHolder(final ViewHolder viewHolder, final int position) {
        // Get the current movie's data at specified position in list
        final @NonNull TrendingMovieViewModel movieData = this.trendingMoviesList.get(position);

        // Bind this movie's name and image to the view generated by the RecyclerView
        viewHolder.trendingMovieName.setText(movieData.getMovieName());
        viewHolder.trendingMovieImage.setImageDrawable(movieData.getMovieImage());
    }

    // Returns the total number of trending movies received from the database
    @Override
    public int getItemCount() {
        return this.trendingMoviesList.size();
    }

    public class ViewHolder extends RecyclerView.ViewHolder {
        public final TextView trendingMovieName;
        public final ImageView trendingMovieImage;

        public ViewHolder(final @NonNull View trendingMovieItemView) {
            super(trendingMovieItemView);
            this.trendingMovieName = trendingMovieItemView.findViewById(R.id.trending_movie_name);
            this.trendingMovieImage = trendingMovieItemView.findViewById(R.id.trending_movie_image);
        }
    }
}
